#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import json
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_GALAXY_PATH = REPO_ROOT / 'data' / 'misp-galaxy'
DEFAULT_OUTPUT = (
    REPO_ROOT / 'misp_stix_converter' / 'stix2misp' / 'converters' / '_galaxy_definitions.py'
)

FILE_HEADER = '''\
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Static galaxy definitions extracted from misp-galaxy.
# Keyed by galaxy type; provides metadata for MISPGalaxy construction.
# kill_chain_order and version intentionally omitted (handled by MISP).
#
# Generated by tools/update_galaxy_definitions.py
# Source:    https://github.com/MISP/misp-galaxy
# Commit:    {commit}
# Tag:       {tag}
# Generated: {timestamp}
'''


def _upstream_info(galaxy_path: Path) -> tuple[str, str]:
    def _git(*args: str) -> str:
        result = subprocess.run(
            ['git', '-C', str(galaxy_path), *args],
            capture_output=True, text=True, check=False
        )
        return result.stdout.strip() if result.returncode == 0 else 'unknown'

    commit = _git('rev-parse', 'HEAD')
    tag = _git('describe', '--tags', '--always')
    return commit, tag


def _load_definitions(galaxy_path: Path) -> dict:
    galaxies_dir = galaxy_path / 'galaxies'
    definitions = {}
    for fpath in sorted(galaxies_dir.glob('*.json')):
        with fpath.open(encoding='utf-8') as fh:
            data = json.load(fh)
        galaxy_type = data.get('type', '')
        if not galaxy_type:
            continue
        definitions[galaxy_type] = {
            'description': data.get('description', ''),
            'icon': data.get('icon', ''),
            'name': data.get('name', ''),
            'namespace': data.get('namespace', ''),
            'type': galaxy_type,
            'uuid': data.get('uuid', ''),
        }
    return definitions


def _render(definitions: dict, commit: str, tag: str) -> str:
    timestamp = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    lines = [FILE_HEADER.format(commit=commit, tag=tag, timestamp=timestamp)]
    lines.append('GALAXY_DEFINITIONS = {')
    for key in sorted(definitions.keys()):
        entry = definitions[key]
        lines.append(f'    {key!r}: {{')
        for field in ('description', 'icon', 'name', 'namespace', 'type', 'uuid'):
            lines.append(f'        {field!r}: {entry[field]!r},')
        lines.append('    },')
    lines.append('}\n')
    return '\n'.join(lines)


def _body_lines(content: str) -> list[str]:
    """Strip generated timestamp line for determinism check."""
    return [ln for ln in content.splitlines() if not ln.startswith('# Generated:')]


def main() -> None:
    parser = argparse.ArgumentParser(
        description='Regenerate _galaxy_definitions.py from the misp-galaxy repository.'
    )
    parser.add_argument(
        '-p', '--misp-galaxy-path',
        default=str(DEFAULT_GALAXY_PATH),
        metavar='PATH',
        help=f'Path to a checked-out misp-galaxy repository (default: {DEFAULT_GALAXY_PATH})',
    )
    parser.add_argument(
        '-o', '--output',
        default=str(DEFAULT_OUTPUT),
        metavar='FILE',
        help=f'Output file (default: {DEFAULT_OUTPUT})',
    )
    parser.add_argument(
        '--check',
        action='store_true',
        help='Exit 1 if generated content differs from the existing file (for CI).',
    )
    args = parser.parse_args()

    galaxy_path = Path(args.misp_galaxy_path).resolve()
    if not (galaxy_path / 'galaxies').is_dir():
        sys.exit(f"Error: {galaxy_path} does not look like a misp-galaxy repo (no galaxies/ subdir)")

    output_path = Path(args.output).resolve()

    commit, tag = _upstream_info(galaxy_path)
    definitions = _load_definitions(galaxy_path)
    content = _render(definitions, commit, tag)

    if args.check:
        if not output_path.exists():
            sys.exit(f"Error: --check requires {output_path} to exist")
        existing = output_path.read_text(encoding='utf-8')
        if _body_lines(content) != _body_lines(existing):
            print(f"FAIL: {output_path} is out of date. Run update_galaxy_definitions.py to refresh.")
            sys.exit(1)
        print(f"OK: {output_path} is up to date.")
        return

    with tempfile.NamedTemporaryFile(
        mode='w', encoding='utf-8', suffix='.py',
        dir=output_path.parent, delete=False
    ) as tmp:
        tmp.write(content)
        tmp_path = Path(tmp.name)

    tmp_path.replace(output_path)
    print(f"Written {len(definitions)} galaxy definitions to {output_path}")
    print(f"  source commit: {commit}  tag: {tag}")


if __name__ == '__main__':
    main()
